version: "3.3"
services:
  postgres:
    image: postgres
    container_name: test_task_reform_postgres
    environment:
      POSTGRES_DB: test-task-reform
      POSTGRES_USER: reform_user
      POSTGRES_PASSWORD: reform_user_pass
      referenceUrl: 'hibernate:spring:entity?dialect=org.hibernate.dialect.PostgreSQL10Dialect&hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy'
    ports:
      - "5433:5432"
  trajectory-app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/test_task_reform_postgres
      - SPRING_DATASOURCE_USERNAME=reform_user
      - SPRING_DATASOURCE_PASSWORD=reform_user_pass
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver